name: 'Map Input'
description: 'Github Action cleaning input by comparing user input against a list in a case-insensitive manner'
author: 'JosephDSchwartz'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  input:
    required: true
    description: The input to map
  input_map:
    required: true
    description: A json object where the property names are the desired output and the values are the list of values, or a single string value, to compare input with.
  get_all_matches:
    required: false
    description: A flag for whether or not to output all matches. By default the output is the first item from the input_map that matches. If this value is true then an array with every match is returned.
    default: 'false'
  error_on_no_match:
    required: false
    description: A flag to determine if the action should exit with an error code or not.
    default: 'false'
  custom_error_message:
    required: false
    description: A custom error message to print out when no match is found and error_on_no_match is true. If no value is given, a generic message is used.
outputs:
  mapped_input:
    description: If get_all_matches is not set or is set to something other than true, then this is the first matching output from the input_map when compared to the input, otherwise it is an array of all matches.
runs:
  using: 'node16'
  main: 'dist/index.js'
